### ISSUE TITLE
TypeError: listen_for_events() got an unexpected keyword argument 'url'

### ISSUE THREAD

**Issue by noobsdt** [nexxai/Substr3am#3]
I am getting error. I used this tool on Parrot OS(```python version: 3.8.6```).
![substream](https://user-images.githubusercontent.com/28983163/98714034-50019880-2380-11eb-9af0-8c17f064c8de.png)

**Comment by nexxai** [comment]
The URL argument is fairly new to the certstream package; just to confirm, what happens when you `pip3 install -r requirements.txt`?

**Comment by noobsdt** [comment]
**Requirement already satisfied!**
![subster](https://user-images.githubusercontent.com/28983163/98844744-ae904a80-2444-11eb-95f3-a5e9cc68d542.png)

**Comment by nexxai** [comment]
I just pushed an updated version of the requirements file so could you pull the latest changes and rerun the pip install again and let me know if that solves the issue?

**Comment by noobsdt** [comment]
Hi, the issue is fixed. By the way, it is taking to much time. I didn't finish the task but it was giving much connection error. Is it normal behaviour?
![ss](https://user-images.githubusercontent.com/28983163/98958912-aeeb1d00-24fa-11eb-8678-63b931f99639.png)

**Comment by nexxai** [comment]
That is normal.  I'm not sure what causes the connection to close but if you just leave it open, it will passively catch any instances for that domain, just like it did in your screenshot.  They will all be logged in the database which you can dump later.
